name: Check GCP action
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v2.1.3'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/gcp-labs-r4latnz5/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider' # In the providerId, the numerical project ID (12 digit number) should be used 
          service_account: 'iam-lab-7-target@gcp-labs-r4latnz5.iam.gserviceaccount.com'                  # instead of the alphanumeric project ID. ex: 
          # 263429482138
          activate_credentials_file: true             # projects/123123123123/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider' 
    - id: debug
      name: debug
      run: |-
        cat "${{ steps.auth.outputs.credentials_file_path }}"
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud config set project gcp-labs-r4latnz5
        gcloud config set account 'iam-lab-7-target@gcp-labs-r4latnz5.iam.gserviceaccount.com'
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud auth list
        gcloud projects list
        gcloud secrets list
        gcloud secrets versions access latest --secret flag_iam_lab_7
